import type { Metadata } from "next";
import SocialMedia from "../components/SocialMedia";


export const metadata: Metadata = {
  title: "Nit | مشروعاتنا",
  description: "Generated by Nit | مشروعاتنا",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <SocialMedia />
    </>
  );
}
