import type { Metadata } from "next";
import BlogHeader from "../components/BlogHeader";
import Footer from "../../components/Footer";

export const metadata: Metadata = {
  title: "Nit | المدونة",
  description: "Generated by Nit | المدونة",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <BlogHeader />
      {children}
      <Footer />
    </div>
  );
}
