import type { Metadata } from "next";
import SocialMedia from "../components/SocialMedia";


export const metadata: Metadata = {
  title: "Nit | اتصل بنا",
  description: "Generated by Nit | اتصل بنا",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
      <SocialMedia />
    </div>
  );
}
