import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import clsx from "clsx";
import Script from "next/script";

const cairo = Cairo({ subsets: ["latin", "arabic"] });

export const metadata: Metadata = {
  title: "Nit",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={clsx(
          `${cairo.className}`,
          { "text-left": locale == "en" },
          { "text-right": locale == "ar" }
        )}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
          <Toaster toastOptions={{ position: "top-right" }} />
        </NextIntlClientProvider>
        <Script
          type="module"
          crossOrigin="anonymous"
          id="IsharatJSWidget"
          data-icon="bottom-20,right-20"
          data-key="68f64ee820c34"
          src="https://jswidget.isharat.net/script-dga-kfu-v1.3.js"
        />
      </body>
    </html>
  );
}
