import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dashboard | Sections",
  description: "Generated by Dashboard | Sections",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
